version: "3.8"

services:
  server:
    container_name: server
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: "GRA1"
      POSTGRES_USER: "amnfpred4FFaaDF"
      POSTGRES_PASSWORD: "DFGfdfgASdc4"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    container_name: auth_db
